### ISSUE TITLE
rt fit error in example jupyter notebook

### ISSUE THREAD

**Issue by LbzSteven** [omarbahri/RuleTransform#1]
Hi, I found a bug in your example jupyter notebook when trying to fit the model. Shown in the image below:
I create the environment of Python 3.6 as the readme instructed:
<img width="866" alt="{E7C6487C-0B9C-4edd-BF6A-C7B6B2D23F1C}" src="https://github.com/omarbahri/RuleTransform/assets/43373047/21fe2f08-7b49-450c-8bcb-cb9f8eb66950">

**Comment by omarbahri** [comment]
Hi! Thanks for pointing this out. I have fixed the issue and updated the notebook.
